[package]
name = "fb2converter_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.35.0", features = ["full"] }
tokio-util = { version = "0.7.10", features = ["compat", "io"] }
futures-util = "0.3.29"

axum = { version = "0.7.2", features = ["multipart"] }
axum-prometheus = "0.5.0"

tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"]}
tower-http = { version = "0.5.0", features = ["trace"] }

async-tempfile = "0.5.0"
uuid = "1.6.1"

sentry = { version = "0.32.0", features = ["debug-images"] }

tokio-cron-scheduler = "0.9.4"
