[tool.poetry]
name = "fb2converter_server"
version = "0.1.0"
description = ""
authors = ["Kurbanov Bulat <kurbanovbul@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.95.0"
python-multipart = "^0.0.6"
aiofiles = "^23.1.0"
uvicorn = {extras = ["standard"], version = "^0.21.1"}
httpx = "^0.23.3"
uvloop = "^0.17.0"
gunicorn = "^20.1.0"
sentry-sdk = "^1.17.0"
fastapi-utils = "^0.2.1"
pydantic = "^1.10.7"

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.21.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.vscode
  | \venv
  | alembic
)/
'''

[tool.ruff]
fix = true
target-version = "py311"
src = ["app"]
line-length=88
ignore = []
select = ["B", "C", "E", "F", "W", "B9", "I001"]
exclude = [
    # No need to traverse our git directory
    ".git",
    # There's no value in checking cache directories
    "__pycache__",
    # The conf file is mostly autogenerated, ignore it
    "src/app/alembic/*",
    # The old directory contains Flake8 2.0
]

[tool.ruff.flake8-bugbear]
extend-immutable-calls = ["fastapi.File", "fastapi.Form"]

[tool.ruff.mccabe]
max-complexity = 15

[tool.ruff.isort]
force-sort-within-sections = true
# only_sections = true
# force_sort_within_sections = true
# lines_after_imports = 2
# lexicographical = true
# sections = ["FUTURE", "STDLIB", "BASEFRAMEWORK", "FRAMEWORKEXT", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
# known_baseframework = ["fastapi",]
# known_frameworkext = ["starlette",]

[tool.ruff.pyupgrade]
keep-runtime-typing = true
